// Utility to generate mobile-friendly plain text summaries from analysis results

export interface AnalysisResult {
  insights: Array<{
    title: string;
    message: string;
    category: string;
    score: number;
  }>;
  trends: Record<string, any>;
  predictions: number[];
  summary_stats: Record<string, any>;
}

export const generateMobileSummary = (analysisResults: AnalysisResult | null): string => {
  if (!analysisResults) {
    return 'No analysis available yet. Upload your data to get insights.';
  }

  let summary = '📊 BUSINESS ANALYTICS SUMMARY\n';
  summary += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n';

  // Top 3 Key Insights
  summary += '🎯 TOP INSIGHTS:\n';
  const topInsights = analysisResults.insights.slice(0, 3);
  topInsights.forEach((insight, idx) => {
    summary += `\n${idx + 1}. ${insight.title}\n`;
    summary += `   ${insight.message}\n`;
    summary += `   Confidence: ${Math.round(insight.score * 100)}%\n`;
  });

  // Trends Summary
  if (Object.keys(analysisResults.trends).length > 0) {
    summary += '\n📈 TRENDS:\n';
    const trendEntries = Object.entries(analysisResults.trends).slice(0, 3);
    trendEntries.forEach(([key, trend]: [string, any]) => {
      const trendName = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
      const direction = trend.direction === 'increasing' ? '↑' : '↓';
      summary += `\n• ${trendName}: ${direction} ${Math.abs(trend.change_percent)}%\n`;
    });
  }

  // Predictions
  if (analysisResults.predictions.length > 0) {
    summary += '\n🔮 FORECAST (Next 7 Days):\n';
    const firstPred = analysisResults.predictions[0];
    const lastPred = analysisResults.predictions[analysisResults.predictions.length - 1];
    const avgPred = analysisResults.predictions.reduce((a, b) => a + b, 0) / analysisResults.predictions.length;
    
    summary += `   Day 1: ${firstPred.toFixed(2)}\n`;
    summary += `   Day 7: ${lastPred.toFixed(2)}\n`;
    summary += `   Average: ${avgPred.toFixed(2)}\n`;
    
    const growth = ((lastPred - firstPred) / firstPred) * 100;
    if (growth > 0) {
      summary += `   Growth: +${growth.toFixed(1)}%\n`;
    } else {
      summary += `   Change: ${growth.toFixed(1)}%\n`;
    }
  }

  // Summary Statistics
  if (Object.keys(analysisResults.summary_stats).length > 0) {
    summary += '\n📊 KEY METRICS:\n';
    const statsEntries = Object.entries(analysisResults.summary_stats).slice(0, 2);
    statsEntries.forEach(([column, stats]: [string, any]) => {
      summary += `\n• ${column}:\n`;
      if (stats.mean !== undefined) summary += `   Avg: ${stats.mean.toFixed(2)}\n`;
      if (stats.min !== undefined) summary += `   Min: ${stats.min.toFixed(2)}\n`;
      if (stats.max !== undefined) summary += `   Max: ${stats.max.toFixed(2)}\n`;
    });
  }

  summary += '\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
  summary += 'Generated by SME Analytics Platform\n';
  summary += new Date().toLocaleString();

  return summary;
};

export const generatePredictionsSummary = (analysisResults: AnalysisResult | null): string => {
  if (!analysisResults) return 'No predictions available';

  let summary = '🔮 PREDICTIONS SUMMARY\n\n';

  // Key predictions
  if (analysisResults.predictions.length > 0) {
    const preds = analysisResults.predictions;
    summary += `Next 7 days forecast:\n`;
    summary += `• Starting: ${preds[0].toFixed(2)}\n`;
    summary += `• Ending: ${preds[preds.length - 1].toFixed(2)}\n`;
    const change = ((preds[preds.length - 1] - preds[0]) / preds[0]) * 100;
    summary += `• Change: ${change > 0 ? '+' : ''}${change.toFixed(1)}%\n\n`;
  }

  // Top trends
  if (Object.keys(analysisResults.trends).length > 0) {
    summary += 'Key Trends:\n';
    Object.entries(analysisResults.trends).slice(0, 3).forEach(([key, trend]: [string, any]) => {
      const name = key.replace(/_/g, ' ');
      summary += `• ${name}: ${trend.direction} ${Math.abs(trend.change_percent)}%\n`;
    });
  }

  return summary;
};

export const generateAnalyticsSummary = (analysisResults: AnalysisResult | null): string => {
  if (!analysisResults) return 'No analytics available';

  let summary = '📊 ANALYTICS SUMMARY\n\n';

  // Summary stats
  if (Object.keys(analysisResults.summary_stats).length > 0) {
    summary += 'Key Metrics:\n';
    Object.entries(analysisResults.summary_stats).slice(0, 3).forEach(([column, stats]: [string, any]) => {
      summary += `\n${column}:\n`;
      if (stats.mean) summary += `  Average: ${stats.mean.toFixed(2)}\n`;
      if (stats.min) summary += `  Min: ${stats.min.toFixed(2)}\n`;
      if (stats.max) summary += `  Max: ${stats.max.toFixed(2)}\n`;
    });
  }

  // Top insights
  if (analysisResults.insights.length > 0) {
    summary += '\nTop Insights:\n';
    analysisResults.insights.slice(0, 3).forEach((insight, idx) => {
      summary += `${idx + 1}. ${insight.title}\n`;
    });
  }

  return summary;
};
